const CHECKOUT_CONST = {
    CHECKOUT_INITIALIZE:"INITIALIZE_CHECKOUT_STEP",
    STEP_STATUS:"SET_CHECKOUT_STEP_STATUS",
    DELIVERY_ADDRESS_SELECTED : "DELIVERY_ADDRESS_SELECTED",
    DELIVERY_ADDRESS_CONFIRMED : "DELIVERY_ADDRESS_CONFIRMED"
}

export default CHECKOUT_CONST;