const CUSTOMER_CONST = {
    CUSTOMER_LOGIN : "CUSTOMER_LOGIN",
    CUSTOMER_LOGOUT : "CUSTOMER_LOGOUT",
    CUSTOMER_ADDRESSES : "SET_CUSTOMER_ADDRESSES",
    DELIVERY_ADDRESS_SELECTED : "DELIVERY_ADDRESS_SELECTED",
    DELIVERY_ADDRESS_CONFIRMED : "DELIVERY_ADDRESS_CONFIRMED",
    CHECKOUT_INITIALIZE:"INITIALIZE_CHECKOUT_STEP",
    CHECKOUT_STEP:"SET_CHECKOUT_STEP"
}

export default CUSTOMER_CONST;