const CUSTOMER_CONST = {
    CUSTOMER_LOGIN : "CUSTOMER_LOGIN",
    CUSTOMER_LOGOUT : "CUSTOMER_LOGOUT",
    CUSTOMER_ADDRESSES : "SET_CUSTOMER_ADDRESSES",
    DELIVERY_ADDRESS_SELECTED : "DELIVERY_ADDRESS_SELECTED",
    DELIVERY_ADDRESS_CONFIRMED : "DELIVERY_ADDRESS_CONFIRMED"
}

export default CUSTOMER_CONST;